#:import get_color_from_hex kivy.utils.get_color_from_hex

<HomePage>:
    md_bg_color: get_color_from_hex("#FFFFFF")

    MDBoxLayout:
        orientation: 'vertical'

        AppBar:

        MDBoxLayout:

            ScrollView:
                bar_width: 0

                MDBoxLayout:
                    adaptive_height: True

                    MDBoxLayout:
                        orientation: 'vertical'
                        adaptive_height: True
                        id: timeline