# -*- coding: utf-8 -*-
"""crypto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pI4r_ZnQhoWCVw6bGu-jrkgHy2yTQkec
"""

!pip install pystan --quiet
!pip install fbprophet --quiet
!pip install yfinance --quiet

import pandas as pd

import yfinance as yf

from fbprophet import Prophet
from fbprophet.plot import plot_plotly, plot_components_plotly

import plotly.graph_objects as go

from datetime import datetime
from datetime import timedelta
import warnings

warnings.filterwarnings('ignore')

pd.options.display.float_format = '${:,.2f}'.format

today = datetime.today().strftime('%Y-%m-%d')
start_date = '2016-01-01'

ethdf = yf.download('BTC-USD',start_date, today)

ethdf.reset_index(inplace=True)
ethdf.columns

df = ethdf[["Date", "Open"]]

new_names = {
    "Date": "ds", 
    "Open": "y",
}

df.rename(columns=new_names, inplace=True)

x = df["ds"]
y = df["y"]

fig = go.Figure()

fig.add_trace(go.Scatter(x=x, y=y))

m = Prophet(
    seasonality_mode="multiplicative" 
)
m.fit(df)
future = m.make_future_dataframe(periods = 365)

forecast = m.predict(future)


next_day = (datetime.today() + timedelta(days=1)).strftime('%Y-%m-%d')

plot_components_plotly(m, forecast)